<?php

/**
 * Implementation of hook_menu().
 */
function webform_status_menu() {
  return array(
    'node/%webform_menu/webform-results/status' => array(
      'title' => t('Status'),
      'page callback' => 'webform_status_status_callback',
      'page arguments' => array(1),
      'access callback' => 'user_access',
      'access arguments' => array('access all webform results'),
      'file' => 'webform_status.inc',
      'type' => MENU_LOCAL_TASK,
    ),
    'admin/reports/webform_status' => array(
      'title' => t('Webform Status Report'),
      'description' => t('Get the status of webform submissions.'),
      'page callback' => 'webform_status_status_all_callback',
      'page arguments' => array(1),
      'access callback' => 'user_access',
      'access arguments' => array('access all webform results'),
      'file' => 'webform_status.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implementation of hook_theme().
 */
function webform_status_theme() {
  return array(
    'webform_status' => array('arguments' => array('node' => NULL, 'reports' => array()), 'template' => 'webform_status', 'file' => 'webform_status.theme.inc'),
    'webform_status_all' => array('arguments' => array('nodes' => array(), 'reports' => array()), 'template' => 'webform_status_all', 'file' => 'webform_status.theme.inc'),
  );
}

/**
 * Page callback for status.
 */
function webform_status_status_callback($node) {
  return theme('webform_status', $node, _webform_status_build_report($node));
}

/**
 * Page callback for all statuses.
 */
function webform_status_status_all_callback() {
  $result = db_query("SELECT * FROM {node} WHERE type = 'contest'");
  
  $nodes = array();
  $reports = array();
  while ( $row = db_fetch_object($result) ) {
    $node = node_load($row->nid);
    $nodes[] = $node;
    $reports[] = _webform_status_build_report($node);
  }

  return theme('webform_status_all', $nodes, $reports);
}